PUSH=calculator.commands.Push
POP=calculator.commands.Pop
PRINT=calculator.commands.Print
DEFINE=calculator.commands.Define
SQRT=calculator.commands.Sqrt
ADD=calculator.commands.Add
+=calculator.commands.Add
SUB=calculator.commands.Subtract
-=calculator.commands.Subtract
MUL=calculator.commands.Multiply
*=calculator.commands.Multiply
DIV=calculator.commands.Divide
/=calculator.commands.Divide